[Service]
Host = "edugroup-ui-go"
Port = 4000
Labels = []
OpenMsg = "edgeX ui started"
StaticResourcesPath = "./static"

#Using an default memory db automatically if not configed here.
[Database]
Host = "172.17.0.1"
Name = "edugroup-ui-go"
Port = 27017
Username = "su"
Password = "su"
  [Database.Scheme]
  User = "user"

[Clients]
    [Clients.CoreData]
    Protocol = 'http'
    Host = 'edgex-core-data'
    Port = 59880
    PathPrefix = "/core-data"

    [Clients.Metadata]
    Protocol = 'http'
    Host = 'edgex-core-metadata'
    Port = 59881
    PathPrefix = "/core-metadata"

    [Clients.CoreCommand]
    Protocol = 'http'
    Host = 'edgex-core-command'
    Port = 59882
    PathPrefix = "/core-command"

    [Clients.Notification]
    Protocol = 'http'
    Host = 'edgex-support-notifications'
    Port = 59860
    PathPrefix = "/support-notification"

    [Clients.Scheduler]
    Protocol = 'http'
    Host = 'edgex-support-scheduler'
    Port = 59861
    PathPrefix = "/support-scheduler"

[Registry]
Host = "edgex-core-consul"
Port = 8500
Type = "consul"
ConfigRegistryStem="edgex/appservices/"
ServiceVersion="1.0"